name: ESPHome Builder
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  lint:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        devices: [ 'example', 'example-with-touch' ]
    steps:
      - uses: actions/checkout@v2
      - uses: esphome/build-action@v1.1.0
        with:
          yaml_file: ${{ matrix.devices }}.yaml
